// JoystickPlugin is licensed under the MIT License.
// Copyright Jayden Maalouf 2026. All Rights Reserved.

#pragma once

// JoystickSDLPrefix.h is generated by the build-sdl action alongside the SDL binaries and
// renames every public SDL symbol to JSP_SDL_*, so the plugin's bundled SDL can never
// collide with an engine-bundled copy (UE 5.7+ links SDL3 into ApplicationCore).
// It must be included before any SDL header and must match the shipped binaries.
// When it is absent, stock (unprefixed) SDL binaries are used instead.
#if defined(__has_include)
	#if __has_include("JoystickSDLPrefix.h")
		#include "JoystickSDLPrefix.h"
	#endif
#endif

#include "SDL.h"
