#!/usr/bin/env bash
# Generates a header that renames every public SDL_x function to JSP_SDL_x,
# so the plugin's SDL can never collide with an engine-bundled SDL (UE 5.7+
# statically links SDL3 into ApplicationCore and other modules, and those
# modules re-export the API - see the header comment in action.yml).
#
# The rename list is derived from SDL's own dynapi override table
# (src/dynapi/SDL_dynapi_overrides.h), which SDL maintains as the canonical
# set of all public entry points - the same mechanism SDL itself uses to
# redirect calls internally.
#
# Usage: generate-prefix-header.sh <sdl-version-for-header-comment>
# Requires SDL_SOURCE_DIR and RUNNER_TEMP in the environment.
# Sets SDL_PREFIX_HEADER via GITHUB_ENV.
set -euo pipefail
SDL_VERSION="$1"

PREFIX_HEADER="$RUNNER_TEMP/JoystickSDLPrefix.h"
{
  echo "// Generated by build-sdl from SDL $SDL_VERSION src/dynapi/SDL_dynapi_overrides.h. Do not edit."
  echo "// Must be included before any SDL header, and must match the shipped JoystickSDL3 binaries."
  echo "#pragma once"
  sed -nE 's/^#define (SDL_[A-Za-z0-9_]+) .*_REAL$/#define \1 JSP_\1/p' \
    "$SDL_SOURCE_DIR/src/dynapi/SDL_dynapi_overrides.h"
} > "$PREFIX_HEADER"

SYMBOL_COUNT=$(grep -c '^#define SDL_' "$PREFIX_HEADER")
echo "Prefixed $SYMBOL_COUNT public SDL symbols"
if [ "$SYMBOL_COUNT" -lt 1000 ]; then
  echo "ERROR: suspiciously few symbols parsed from SDL_dynapi_overrides.h" >&2
  exit 1
fi

echo "SDL_PREFIX_HEADER=$PREFIX_HEADER" >> "$GITHUB_ENV"
